name: tester

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, debian:latest, fedora-latest]
    container:
      image: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: execute permission
        run: chmod +x terraform-installer.sh

      - name: run script
        run: ./terraform-installer.sh

      - name: verify
        run: terraform --version
