name: Test Terraform Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - run: apt-get update && apt-get install -y wget gpg sudo
      - run: sh ./terraform-installer.sh
      - run: terraform --version

  debian:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - uses: actions/checkout@v3
      - run: apt-get update && apt-get install -y wget gpg sudo
      - run: sh ./terraform-installer.sh
      - run: terraform --version

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - uses: actions/checkout@v3
      - run: dnf install -y wget gnupg sudo
      - run: sh ./terraform-installer.sh
      - run: terraform --version

  zorinos:
    runs-on: ubuntu-latest
    container:
      image: zorinos:latest
    steps:
      - uses: actions/checkout@v3
      - run: apt-get update && apt-get install -y wget gpg sudo
      - run: sh ./terraform-installer.sh
      - run: terraform --version

  linuxmint:
    runs-on: ubuntu-latest
    container:
      image: linuxmint:latest
    steps:
      - uses: actions/checkout@v3
      - run: apt-get update && apt-get install -y wget gpg sudo
      - run: sh ./terraform-installer.sh
      - run: terraform --version

  centos:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream8
    steps:
      - uses: actions/checkout@v3
      - run: yum install -y wget gnupg sudo
      - run: sh ./terraform-installer.sh
      - run: terraform --version

  rhel:
    runs-on: ubuntu-latest
    container:
      image: redhat/ubi8:latest
    steps:
      - uses: actions/checkout@v3
      - run: yum install -y wget gnupg sudo
      - run: sh ./terraform-installer.sh
      - run: terraform --version

  amazonlinux:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:latest
    steps:
      - name: Install tar
        run: yum install -y tar
      - uses: actions/checkout@v3
      - run: yum install -y wget gnupg sudo
      - run: sh ./terraform-installer.sh
      - run: terraform --version
